TARGET   = fluidanimate
OBJS     = serial.o cellpool.o

# To enable visualization comment out the following lines (don't do this for benchmarking)
#OBJS     += fluidview.o
#CXXFLAGS += -DENABLE_VISUALIZATION
#LIBS     += -lglut

NLD = $(NAUT)/user/framework/nld-cxx-noelle-ubuntu

all: serial fluidcmp

serial: $(OBJS)
	$(NLD) $(KARAT) $(OBJS) -o $(TARGET)

%.o : %.cpp
	$(CXX) $(CXXFLAGS) -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -c $<

fluidcmp: fluidcmp.cpp
	rm -rf fluidcmp
	$(CXX) fluidcmp.cpp -o fluidcmp
clean:
	rm -rf $(TARGET) 
	rm -rf fluidcmp
