#!/bin/bash

# This script needs to be extended to automatically
# find the paths to the crt objects

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
fi

REALPATH=$(realpath $0)
DIRNAME=$(dirname $REALPATH)

CRTGEN_DIR=/usr/lib64
CRTBE_DIR=/usr/lib/gcc/x86_64-redhat-linux/8

OUT_FLAG=$(echo "$*" | grep -Poe "-o\ .*?(\ |$)")
echo $OUT_FLAG

make framework -C $DIRNAME

if [[ $* != *-nokarat* ]]; then
  USER_OBJ=target.o
  BLOB_OBJ=blob.o
  BLOB_BC=blob.bc
  BLOB_SIMPLIFY_BC=blob_simplify.ll
  BLOB_OPT_BC=blob_opt.ll
  KARAT_OUT=karat.out
  BLOB_KOBJ=blob.kobj.o
  LD=ld
  EXTRACTBC=extract-bc
  NORM=noelle-norm
  ME=noelle-load

  set -x

  # ld -r $* $DIRNAME/glue.o $DIRNAME/framework.o -o ${BLOB_OBJ}
  ld -r $* $DIRNAME/glue.o -o ${BLOB_OBJ} 

  ${EXTRACTBC} ${BLOB_OBJ}
  mv ${BLOB_OBJ}.bc ${BLOB_BC}

  # Run select loop simplification passes
  ${NORM} -S ${BLOB_BC} -o ${BLOB_SIMPLIFY_BC}

  # Run KARAT pass
  ${ME} -load ~/CAT/lib/KARAT.so -karat -target-user -S ${BLOB_SIMPLIFY_BC} -o ${BLOB_OPT_BC} &> ${KARAT_OUT}
  clang -mno-red-zone -fPIC -c ${BLOB_OPT_BC} -o target.o
else
  echo "Called with -nokarat"
  set -x
  SNIPPED_ARGS=$(echo $* | sed 's/-nokarat//')
  ld -r $SNIPPED_ARGS $DIRNAME/glue.o $DIRNAME/framework.o -o target.o
fi

# /home/arn9233 is included because of static libomp.a, which doesn't typically exist.
# framework_low_level has to be linked in this step, otherwise the multiboot header will be discarded.
ld -static -pie --no-dynamic-linker \
  -T $DIRNAME/framework.lds -dp -z max-page-size=0x1000 -z relro -z now \
  $CRTGEN_DIR/rcrt1.o $CRTGEN_DIR/crti.o $CRTBE_DIR/crtbeginS.o \
  -L/home/arn9233/ -L$CRTBE_DIR/ -L$CRTGEN_DIR -L/usr/lib \
  $DIRNAME/framework.o target.o $DIRNAME/framework_low_level.o \
  -lm -ldl --start-group -lgcc -lpthread -lc -lrt --end-group \
  $CRTBE_DIR/crtendS.o $CRTGEN_DIR/crtn.o \
  $OUT_FLAG
