obj-$(NAUT_CONFIG_ASPACE_BASE)   += base/
obj-$(NAUT_CONFIG_ASPACE_PAGING) += paging/
obj-$(NAUT_CONFIG_ASPACE_CARAT)  += carat/

# Only compile the region tracking data structure if one of the data structures are required
obj-$(NAUT_CONFIG_ASPACE_PAGING_REGION_RB_TREE) += region_tracking/
obj-$(NAUT_CONFIG_ASPACE_PAGING_REGION_SPLAY_TREE) += region_tracking/
obj-$(NAUT_CONFIG_ASPACE_PAGING_REGION_LINKED_LIST) += region_tracking/
obj-$(NAUT_CONFIG_ASPACE_CARAT_REGION_RB_TREE) += region_tracking/
obj-$(NAUT_CONFIG_ASPACE_CARAT_REGION_SPLAY_TREE) += region_tracking/
obj-$(NAUT_CONFIG_ASPACE_CARAT_REGION_LINKED_LIST) += region_tracking/