obj-y = node_struct.o

obj-$(NAUT_CONFIG_ASPACE_PAGING_REGION_RB_TREE) += mm_rb_tree.o
obj-$(NAUT_CONFIG_ASPACE_CARAT_REGION_RB_TREE) += mm_rb_tree.o

obj-$(NAUT_CONFIG_ASPACE_PAGING_REGION_SPLAY_TREE) += mm_splay_tree.o
obj-$(NAUT_CONFIG_ASPACE_CARAT_REGION_SPLAY_TREE) += mm_splay_tree.o

obj-$(NAUT_CONFIG_ASPACE_PAGING_REGION_LINKED_LIST) += mm_linked_list.o
obj-$(NAUT_CONFIG_ASPACE_CARAT_REGION_LINKED_LIST) += mm_linked_list.o

