#!/bin/bash -x

BENCH=$1
FILE_NAME=$2
KARAT_FLAGS=$3
MNT=$4

PARSEC=${NAUT}/user/test/parsec

# NAUT=environment var is set to your top level nautilus directory
FW=${NAUT}/user/framework
echo ${NAUT} ;
echo ${FW} ;

# Check for ramdisk in nautilus directory
if [ ! -f "${NAUT}/ramdisk.img" ]
then
    echo "ramdisk.img is missing in your Nautilus directory!" ;
    exit 1 ;
fi


# Set up sub-parsec directory terribly
SUB_PS="apps"
if [[ "$BENCH" == "streamcluster" ]]
then
    SUB_PS="kernels" ;
    echo ${SUB_PS} ;
elif [[ "$BENCH" == "canneal" ]]
then
    SUB_PS="kernels" ;
    echo ${SUB_PS} ;
else
    echo ${SUB_PS} ;
fi

BENCH_DIR=${PARSEC}/pkgs/${SUB_PS}/${BENCH}

# Mount
echo "Mounting ..."
mkdir -p ${MNT}
guestunmount ${MNT} ;
guestmount -a ${NAUT}/ramdisk.img -m /dev/sda ${MNT} ;


# Set up user framework, FW is set in environment
echo "Setting up framework ..."
cd ${FW} && \
    make clean ; \
    make framework ;


# Set up NAS suite, build benchmark
echo "Building benchmark ..."
export KARAT=${KARAT_FLAGS} ; 
cd ${PARSEC} && \
    ./bin/parsecmgmt -a uninstall -p ${BENCH} -c clang && \
    ./bin/parsecmgmt -a build -p ${BENCH} -c clang && \
    cp ${BENCH_DIR}/obj/amd64-linux.clang/${BENCH} ${MNT}/${FILE_NAME^^}.EXE && \
    cp ${BENCH_DIR}/inputs/I.txt ${MNT}/${FILE_NAME^^}I.TXT \


# Unmount 
echo "Unmounting...";
guestunmount ${MNT} ;
touch ${NAUT}/src/asm/ramdisk.s
echo "Done!"




